name: Build Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install GNU Arm Embedded Toolchain
      uses: ryanwinter/arm-none-eabi-gcc@master
      with:
        release: '10.3-2021.10'

    - uses: actions/checkout@v3

    - name: Checkout Firmware
      run: git submodule update --init --recursive Firmware/blackmagic

    - name: Build
      working-directory: ./Firmware/blackmagic
      run: make PROBE_HOST=revp
